artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://storage.googleapis.com/kaggle-competitions-data/kaggle-v2/48160/5110038/bundle/archive.zip?GoogleAccessId=web-data@kaggle-161607.iam.gserviceaccount.com&Expires=1731688196&Signature=gu3WsB6TtmgmmF3MbcR1W0xQNACCMbolQ1LCt5JmcnEXcYfdVJpJ%2FqNuG%2BIFTmiDmWjN9d%2FUYeDNSKKd6WEeCVmwiJJsk6prjItZhDvG0KlYYY3KlKgz6laj7Tb770iKI%2FAI%2F3qGFjqHWR%2BKrXp0lefDErA4BGsBvVGAuOZWIG36jzaoxlUcZBioynEo%2Bd1uYMJkXrdMbSIrYuNw4LpEtMAqbbCjjsHcqS9BouD509cNXThWMtGlckRaCbc14K3fmb2irO4pigw%2FonFid6Ib2GLQfbvgpE8m4fT0%2B%2BurcqG5CRXT9%2BiNeXOx1P4wWd0%2BV4vgA7%2BNlmRuWwkcD077bg%3D%3D&response-content-disposition=attachment%3B+filename%3Dml-olympiad-can-you-guess-beer-style.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/winequality-red.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json
